# Image de base Python 3.12
FROM python:3.12

# Mainteneur de l'image
LABEL maintainer="Ilyes"
# Description de l'application
LABEL description="Application Flask pour les retours de formation"

# Variable Flask : fichier principal
ENV FLASK_APP=app.py
# Variable Flask : environnement de développement
ENV FLASK_ENV=dev

# Répertoire de travail dans le conteneur
WORKDIR /app

# Copie des dépendances
COPY requirements.txt .
# Copie du dossier de l'application
COPY app app
# Copie du fichier principal
COPY app.py .

# Installation des dépendances (sans cache)
RUN pip install --no-cache-dir -r requirements.txt

# Création d'un utilisateur non-root pour la sécurité
RUN useradd -ms /bin/bash appuser
# Utilisation de l'utilisateur non-root
USER appuser

# Port exposé par l'application
EXPOSE 5000

# Commande de démarrage de l'application
CMD ["python", "app.py"]


### Commandes pour construire l'image Docker
# docker build -t lepont-feedback .
# docker run -p 5000:5000 lepont-feedback

## vérification que l'application Flask s'exécute correctement dans le conteneur Docker
# http://localhost:5000
